name: Publish to GitHub Pages

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Setup Node.js
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
      with:
        node-version: '16.x'

    # Install dependency
    - name: Install dependencies
      run: npm install

    # Check
    - name: lint
      run: npm run lint

    # Build
    - name: Build webpack
      run: npm run production

    - name: Publish generated content to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: dist
